#!/bin/sh
set -e

cd ~

# Install Homebrew
if [ ! -f /usr/local/bin/brew ]
	then
		echo "Installing Homebrew..."
		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
	else
		echo "Homebrew already installed."
fi

# Clone my dotfiles
if [ ! -d ~/dotfiles ]
	then
		cd ~/.ssh
		ssh-keygen
		pbcopy < ~/.ssh/id_rsa.pub
		echo "公開鍵をGitHubに登録しましたか？"
		select yn in "Yes"; do
			case $yn in
				Yes ) break;;
			esac
		done

		echo "Cloning dotfiles..."
		git clone git@github.com:watsuyo/dotfiles.git
	else
		echo "dotfiles already cloned."
fi

# Install some software
echo "Installing some software & library..."
brew bundle -v --file=./dotfiles/Brewfile

# パスワード等必要情報を入力
touch ~/dotfiles/shell/state.txt
source ~/dotfiles/shell/input/password

source ~/dotfiles/shell/state.txt

echo $PASSWORD | sudo -S spctl --master-disable > /dev/null 2>&1

if [ ! -d ~/.config ]
	then
		echo "Creating ~/.config directory..."
		mkdir ~/.config
fi

echo "zsh-autosuggestionsをインストール"
sh ~/dotfiles/shell/zsh-autosuggestions

echo "Alfredの設定を読み込む"
sh ~/dotfiles/shell/alfred

echo "Zpreztoの設定を読み込む"
sh ~/dotfiles/shell/zprezto

echo "zshの設定を読み込む"
source ~/.zshrc

# echo "Carelyのセットアップ"
# sh ~/dotfiles/shell/carely

echo "シンボリックリンクを貼る"
echo "Symlinking dotfiles..."
sh ~/dotfiles/shell/symlink && echo "Done."
