#!/bin/sh

if [ ! ~/.zprezto ]
	then
		echo "Installing Zprezto..."
		cd ~
		git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
		zsh
		setopt EXTENDED_GLOB
		echo "hoge"
		`for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
			ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
		done`
	else
		echo "Zprezto already installed."
fi
