#!/bin/sh

if [ ! -d ~/.zsh/zsh-autosuggestions ]
	then
		echo "Installing zsh-autosuggestions..."
		git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions
		source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
fi
