#!/bin/sh

function input_pass() {
	echo "Passwordを変数に保存: "
	read password
	echo "👆で保存しますか？"
}

input_pass

select yn in "Yes" "No"; do
	case $yn in
		Yes ) echo "PASSWORD=\"$password\"" >> ~/dotfiles/shell/state.txt && break;;
		No ) input_pass
	esac
done
